const { DateTime } = require("luxon");

module.exports = function(eleventyConfig) {

  // ── Pass-through copies (existing static files) ──
  eleventyConfig.addPassthroughCopy("index.html");
  eleventyConfig.addPassthroughCopy("welcome.html");
  eleventyConfig.addPassthroughCopy("privacy.html");
  eleventyConfig.addPassthroughCopy("terms.html");
  eleventyConfig.addPassthroughCopy("unsubscribe.html");
  // MTA-STS policy file served from mta-sts.mondayclinicalbrief.co.uk (Netlify
  // domain alias) for receiving servers that enforce TLS to our MX.
  eleventyConfig.addPassthroughCopy(".well-known");
  eleventyConfig.addPassthroughCopy("_redirects");
  eleventyConfig.addPassthroughCopy("netlify");
  eleventyConfig.addPassthroughCopy("admin");
  eleventyConfig.addPassthroughCopy("assets");
  // Per-specialty deep-dive sample digests, generated by ~/mcb-sample-pages/
  // build_sample_pages.py from backend/logs/articles_<slug>_<date>.json.
  eleventyConfig.addPassthroughCopy("samples");
  eleventyConfig.addPassthroughCopy("robots.txt");

  // ── Date filters ──
  eleventyConfig.addFilter("readableDate", (dateObj) => {
    return DateTime.fromJSDate(dateObj, { zone: "utc" }).toFormat("d LLLL yyyy");
  });

  eleventyConfig.addFilter("isoDate", (dateObj) => {
    return DateTime.fromJSDate(dateObj, { zone: "utc" }).toISO();
  });

  // ── Reading time filter ──
  eleventyConfig.addFilter("readingTime", (content) => {
    if (!content) return "5 min read";
    // Strip HTML tags for more accurate word count
    const text = String(content).replace(/<[^>]+>/g, '');
    const words = text.split(/\s+/).filter(w => w.length > 0).length;
    if (words < 50) return "5 min read"; // fallback for short strings like descriptions
    const mins = Math.ceil(words / 220);
    return `${mins} min read`;
  });

  // ── Signup block placement ──
  // Puts a post's signup block just before its nth <h2>: after the opening
  // section, which answers what the reader searched for, rather than at the
  // foot of the page where few readers get to. A post with fewer headings
  // gets the block at the end of its body instead.
  eleventyConfig.addFilter("insertBeforeH2", (content, html, n = 2) => {
    const body = String(content);
    let at = -1;
    for (let i = 0; i < n; i++) {
      at = body.indexOf("<h2", at + 1);
      if (at === -1) return body + String(html);
    }
    return body.slice(0, at) + String(html) + body.slice(at);
  });

  // ── Blog post collection ──
  eleventyConfig.addCollection("posts", function(collectionApi) {
    return collectionApi.getFilteredByGlob("blog/**/*.md").sort((a, b) => {
      return b.date - a.date;
    });
  });

  // ── Cluster collections ──
  eleventyConfig.addCollection("cluster1", function(collectionApi) {
    return collectionApi.getFilteredByGlob("blog/medical-journal-digest/**/*.md").sort((a, b) => b.date - a.date);
  });

  eleventyConfig.addCollection("cluster2", function(collectionApi) {
    return collectionApi.getFilteredByGlob("blog/cpd-reading-tool/**/*.md").sort((a, b) => b.date - a.date);
  });

  eleventyConfig.addCollection("cluster3", function(collectionApi) {
    return collectionApi.getFilteredByGlob("blog/journal-summary-subscription/**/*.md").sort((a, b) => b.date - a.date);
  });

  eleventyConfig.addCollection("cluster4", function(collectionApi) {
    return collectionApi.getFilteredByGlob("blog/dentistry/**/*.md").sort((a, b) => b.date - a.date);
  });

  // ── Markdown config with anchor links ──
  let markdownIt = require("markdown-it");
  let markdownItAnchor = require("markdown-it-anchor");
  let mdOptions = { html: true, breaks: false, linkify: true };
  let mdLib = markdownIt(mdOptions).use(markdownItAnchor, {
    permalink: false,
    level: [2, 3]
  });
  eleventyConfig.setLibrary("md", mdLib);

  return {
    dir: {
      input: ".",
      includes: "_includes",
      output: "dist"
    },
    templateFormats: ["md", "njk"],
    markdownTemplateEngine: "njk",
    htmlTemplateEngine: "njk"
  };
};
